name = "DictLearning"
uuid = "c475dd53-10e7-4fe9-b76b-ddd412c453de"
authors = ["SimonRuetz <simon.ruetz@ubik.ac.at> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
